"""init_db

Revision ID: e754d84c8c08
Revises: 
Create Date: 2019-08-09 22:13:44.838089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e754d84c8c08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('produced_timestamp', sa.Numeric(precision=16, scale=6, decimal_return_scale=6), nullable=False),
    sa.Column('consumed_timestamp', sa.Numeric(precision=16, scale=6, decimal_return_scale=6), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('operation_str', sa.String(), nullable=False),
    sa.Column('operation_type', sa.String(length=1), nullable=False),
    sa.Column('children_idents', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('snapshot_storage',
    sa.Column('ident', sa.String(length=32), nullable=False),
    sa.Column('parent_ident', sa.String(length=32), nullable=True),
    sa.Column('parent_timestamp', sa.Numeric(precision=16, scale=6, decimal_return_scale=6), nullable=True),
    sa.Column('type', sa.String(length=1), nullable=False),
    sa.Column('disk_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('image_path', sa.String(length=250), nullable=False),
    sa.Column('new_storage_size', sa.BigInteger(), nullable=True),
    sa.Column('start_timestamp', sa.Numeric(precision=16, scale=6, decimal_return_scale=6), nullable=True),
    sa.Column('finish_timestamp', sa.Numeric(precision=16, scale=6, decimal_return_scale=6), nullable=True),
    sa.Column('tree_ident', sa.String(length=40), nullable=False),
    sa.Column('file_level_deduplication', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_ident'], ['snapshot_storage.ident'], ),
    sa.PrimaryKeyConstraint('ident'),
    sa.UniqueConstraint('ident')
    )
    op.create_index(op.f('ix_snapshot_storage_tree_ident'), 'snapshot_storage', ['tree_ident'], unique=False)
    op.create_table('hash',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('storage_ident', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.Numeric(precision=16, scale=6, decimal_return_scale=6), nullable=False),
    sa.Column('version', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=1), nullable=False),
    sa.Column('path', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['storage_ident'], ['snapshot_storage.ident'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hash')
    op.drop_index(op.f('ix_snapshot_storage_tree_ident'), table_name='snapshot_storage')
    op.drop_table('snapshot_storage')
    op.drop_table('journal')
    # ### end Alembic commands ###
