"""empty message

Revision ID: 3d282628ac0f
Revises: 4955c9a64c1c
Create Date: 2019-08-19 16:42:30.852171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d282628ac0f'
down_revision = '4955c9a64c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'snapshot_storage', ['ident'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'snapshot_storage', type_='unique')
    # ### end Alembic commands ###
